### PR TITLE
Fix bug writing unknown tags

### PR DESCRIPTION
**Pull request by simon-20**
This fixes the bug writing unknown tags. With this change, unknown tags will be written out as they were in the original file.

### CODE REVIEW

**Review by shapiromatron — CHANGES_REQUESTED** [review]
Thanks for the submission - it looks like a valuable feature! Could you please write a test as well for this?

**Comment by simon-20** [comment]
Yes, I will do, on both counts. Should the `make test` command work/be working on Windows?

**Comment by shapiromatron** [comment]
> Yes, I will do, on both counts. Should the `make test` command work/be working on Windows?

I dont think it'll work on windows. The makefile just calls pytest, so you can just call that directly:

https://github.com/MrTango/rispy/blob/d795f51264823ce666b36dd1538d3c8955f6d26f/Makefile#L51-L52

**Review by J535D165 — APPROVED** [review]

**Comment by simon-20** [comment]
> > Yes, I will do, on both counts. Should the `make test` command work/be working on Windows?
> 
> I dont think it'll work on windows. The makefile just calls pytest, so you can just call that directly:
> 
> https://github.com/MrTango/rispy/blob/d795f51264823ce666b36dd1538d3c8955f6d26f/Makefile#L51-L52

I did get the tests to work on Windows; I had a misconfiguration of `make` on my end.

**Review by shapiromatron — APPROVED** [review]
LGTM - great addition!

**Review by shapiromatron — APPROVED** [review]

**Pull request merged**
