### PR TITLE
Added .editorconfig

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by shapiromatron** [comment]
@KOLANICH we just made some updates to use black and other code style checks. It doesn't look like it, but would any of these config settings conflict w/ the new tooling?

**Comment by MrTango** [comment]
I prefer to have all these settings in the setup.cfg, when ever posible.
For flake8 and black thats the case.

**Comment by shapiromatron** [comment]
@KOLANICH  bump on my prior comment :)

**Comment by shapiromatron** [comment]
@KOLANICH closing, hearing nothing. If you'd like to make edits please feel free to reopen/resubmit.

**Comment by KOLANICH** [comment]
>It doesn't look like it, but would any of these config settings conflict w/ the new tooling?

Shouldn't. Both adhere to the same standard.

>do we need these new configuration files? It seems like this is now taken-care of automatically.

We do. These are different config files for different tools and the transformations are applied in different times and differently. `.editorconfig` applies the transformations while you edit the file. If there is no `.editorconfig` (or no support for it or somethingwith similar functionality) editors having tabs set by default (changing editors global settings is inacceptible since lot of people prefer tabs) will cause mixing or tabs and spaces, which is not allowed in python. `black` parses only valid python code, so it will fail in this case. `autopep8` may succeed though.

**Comment by MrTango** [comment]
Editors with Python support usually also read the setup.cfg and take the settings from, in vs code this works fine. 
Do you have an example of an editor who does not take them from setup.cfg but only from .editorconfig?

**Comment by KOLANICH** [comment]
Notepad++ with editorconfig  plugin

**Pull request closed without merging**
