### PR TITLE
Moved the metadata into setup.cfg

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by shapiromatron** [comment]
@KOLANICH this still seems like a good change, but with the recent release there are some conflicts. Would you mind resubmitting?

**Comment by MrTango** [comment]
related to #22

**Comment by shapiromatron** [comment]
@KOLANICH do you plan on providing updates? If not, this PR may be closed; there are a number of merge-conflicts from our recent update to the software

**Comment by shapiromatron** [comment]
@KOLANICH also, if you want us to take this over, let us know.

**Comment by shapiromatron** [comment]
@KOLANICH please indicate either way.

**Comment by shapiromatron** [comment]
Closing; no recent activity.

**Pull request closed without merging**
